import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import tailwindcss from '@tailwindcss/vite';
import {loadEnv} from 'vite';
const env=loadEnv(process.env.NODE_ENV||'production',process.cwd(),'PUBLIC_');
const productionSite = 'https://wanderburg.ymmyi.wiki';
const configuredSite = (process.env.PUBLIC_SITE_URL || env.PUBLIC_SITE_URL || productionSite).trim();
const siteUrl = new URL(configuredSite || productionSite);
if (!['http:', 'https:'].includes(siteUrl.protocol) || siteUrl.username || siteUrl.password || siteUrl.pathname !== '/' || siteUrl.search || siteUrl.hash) throw new Error('PUBLIC_SITE_URL must be an HTTP(S) origin without a path, credentials, query, or fragment');
const isLocal = siteUrl.hostname === 'localhost' || siteUrl.hostname.endsWith('.localhost') || siteUrl.hostname === '[::1]' || siteUrl.hostname === '0.0.0.0' || /^127\./.test(siteUrl.hostname);
const site = isLocal ? productionSite : siteUrl.origin;
export default defineConfig({site, trailingSlash:'always', output:'static', integrations:[mdx()], vite:{plugins:[tailwindcss()]}});
